// This file will be automatically generated by FlutterFire CLI.
// To generate it, run: flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default Firebase options for different platforms.
/// This will be generated by FlutterFire CLI.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // TODO: Dynamically select based on build flavor
    // Currently defaulting to staging for testing
    // Change to 'production' ONLY after staging is fully tested and ready
    return _getOptionsForEnvironment('staging');
  }

  static FirebaseOptions _getOptionsForEnvironment(String environment) {
    if (environment == 'production') {
      return _getProductionOptions();
    } else {
      return _getStagingOptions();
    }
  }

  static FirebaseOptions _getStagingOptions() {
    if (kIsWeb) {
      throw UnsupportedError(
        'Web is not configured yet for staging environment.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return androidStaging;
      case TargetPlatform.iOS:
        return iosStaging;
      case TargetPlatform.macOS:
        return macosStaging;
      case TargetPlatform.windows:
        return windowsStaging;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions _getProductionOptions() {
    if (kIsWeb) {
      throw UnsupportedError(
        'Web is not configured yet for production environment.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return androidProduction;
      case TargetPlatform.iOS:
        return iosProduction;
      case TargetPlatform.macOS:
        return macosProduction;
      case TargetPlatform.windows:
        return windowsProduction;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // STAGING ENVIRONMENT CONFIGURATION
  static const FirebaseOptions androidStaging = FirebaseOptions(
    apiKey: 'AIzaSyBkyiyOzJHVxurTwT22LRWQiugGq9hDbqI',
    appId: '1:641865839333:android:ca1bd459b8d557ace3da0c',
    messagingSenderId: '641865839333',
    projectId: 'comnecter-mobile-staging-711a7',
    storageBucket: 'comnecter-mobile-staging-711a7.firebasestorage.app',
    // TODO: Add measurementId after GA4 data stream is created in Firebase Console
    // measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions iosStaging = FirebaseOptions(
    apiKey: 'AIzaSyBKEFY_isLeqlfbbiNes7HMFub2C8PANeM',
    appId: '1:641865839333:ios:00da01cbc3f0f74ce3da0c',
    messagingSenderId: '641865839333',
    projectId: 'comnecter-mobile-staging-711a7',
    storageBucket: 'comnecter-mobile-staging-711a7.firebasestorage.app',
    iosBundleId: 'com.comnecter.mobile.staging',
  );

  static const FirebaseOptions macosStaging = FirebaseOptions(
    apiKey: 'AIzaSyBKEFY_isLeqlfbbiNes7HMFub2C8PANeM',
    appId: '1:641865839333:ios:00da01cbc3f0f74ce3da0c',
    messagingSenderId: '641865839333',
    projectId: 'comnecter-mobile-staging-711a7',
    storageBucket: 'comnecter-mobile-staging-711a7.firebasestorage.app',
    iosBundleId: 'com.comnecter.mobile.staging',
  );

  static const FirebaseOptions windowsStaging = FirebaseOptions(
    apiKey: 'AIzaSyBkyiyOzJHVxurTwT22LRWQiugGq9hDbqI',
    appId: '1:641865839333:android:ca1bd459b8d557ace3da0c',
    messagingSenderId: '641865839333',
    projectId: 'comnecter-mobile-staging-711a7',
    storageBucket: 'comnecter-mobile-staging-711a7.firebasestorage.app',
  );

  // PRODUCTION ENVIRONMENT CONFIGURATION
  static const FirebaseOptions androidProduction = FirebaseOptions(
    apiKey: 'AIzaSyBNeBu6-zpkjAdYN3ePFR2RRcYv48Dr2U4',
    appId: '1:284330914957:android:21271ad129d9a7274e9ec4',
    messagingSenderId: '284330914957',
    projectId: 'comnecter-mobile-product-dc4ea',
    storageBucket: 'comnecter-mobile-product-dc4ea.firebasestorage.app',
  );

  static const FirebaseOptions iosProduction = FirebaseOptions(
    apiKey: 'AIzaSyChZdndUyJruMGhrQ-z5m5SMg2ALPCHzdY',
    appId: '1:284330914957:ios:2d3f8ae1567acf444e9ec4',
    messagingSenderId: '284330914957',
    projectId: 'comnecter-mobile-product-dc4ea',
    storageBucket: 'comnecter-mobile-product-dc4ea.firebasestorage.app',
    iosBundleId: 'com.comnecter.mobile.production',
  );

  static const FirebaseOptions macosProduction = FirebaseOptions(
    apiKey: 'AIzaSyChZdndUyJruMGhrQ-z5m5SMg2ALPCHzdY',
    appId: '1:284330914957:ios:2d3f8ae1567acf444e9ec4',
    messagingSenderId: '284330914957',
    projectId: 'comnecter-mobile-product-dc4ea',
    storageBucket: 'comnecter-mobile-product-dc4ea.firebasestorage.app',
    iosBundleId: 'com.comnecter.mobile.production',
  );

  static const FirebaseOptions windowsProduction = FirebaseOptions(
    apiKey: 'AIzaSyBNeBu6-zpkjAdYN3ePFR2RRcYv48Dr2U4',
    appId: '1:284330914957:android:21271ad129d9a7274e9ec4',
    messagingSenderId: '284330914957',
    projectId: 'comnecter-mobile-product-dc4ea',
    storageBucket: 'comnecter-mobile-product-dc4ea.firebasestorage.app',
  );

  // Legacy configurations (kept for backward compatibility)
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3f8zAdKxm8HXWHJCiMNwVW0kkZhERjhw',
    appId: '1:887865244956:web:temp-web-app-id',
    messagingSenderId: '887865244956',
    projectId: 'comnecter-mobile-aa30b',
    authDomain: 'comnecter-mobile-aa30b.firebaseapp.com',
    storageBucket: 'comnecter-mobile-aa30b.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = androidStaging;
  static const FirebaseOptions ios = iosStaging;
  static const FirebaseOptions macos = macosStaging;
  static const FirebaseOptions windows = windowsStaging;
}
